# starship.toml
# @author deng
# since 2024 2025 2026

add_newline = false
follow_symlinks = false
# palette = 'catppuccin_mocha'

# [➔](bold green) \
# $cmd_duration \

format = """
$os\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$all\
$character\
"""

# right_format = """
# """

# [line_break]
# disabled = true

[os]
disabled = false
format = '[$symbol]($style)'

# [username]
# style_user = 'bold green'
# style_root = 'bold green'
# show_always = true
# format = '[$user]($style)@'
#
# [hostname]
# style = 'bold green'
# ssh_only = false
# ssh_symbol = ' '
# trim_at = ''
# format = '[$ssh_symbol$hostname]($style) '

[directory]
style = 'bold blue'
format = '[$path]($style) '
read_only = ' 󰌾'
truncation_length = 3

[character]
# success_symbol = '[\$](bold green)'
success_symbol = '[➔](bold green)'
error_symbol = '[✘](bold red)'
# vimcmd_symbol = '[➔](bold green)'

[git_branch]
# symbol = '   '
symbol = ' '
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
# options available for format
staged     = '+'
modified   = '!'
renamed    = '»'
deleted    = '-'
untracked  = '?'
stashed    = '≡'
conflicted = '✖'
ahead    = '↑${count}'
behind   = '↓${count}'
diverged = '↕${ahead_count}↓${behind_count}'

[aws]
symbol = ' '

[azure]
symbol = ' '

[package]
symbol = '󰏗 '
format = '[$symbol$version]($style) '

[buf]
symbol = ' '
format = '[$symbol($version )]($style)'

[bun]
symbol = ' '
format = '[$symbol($version )]($style)'

[c]
symbol = ' '
format = '[$symbol($version(-$name) )]($style)'

[cpp]
symbol = ' '
format = '[$symbol($version(-$name) )]($style)'

[cmake]
symbol = ' '
format = '[$symbol($version )]($style)'

[cobol]
symbol = ' '
format = '[$symbol($version )]($style)'

[conda]
symbol = ' '
format = '[$symbol$environment]($style) '

[container]
symbol = ' '

[crystal]
symbol = ' '
format = '[$symbol($version )]($style)'

[dart]
symbol = ' '
format = '[$symbol($version )]($style)'

[deno]
symbol = ' '
format = '[$symbol($version )]($style)'

[direnv]
symbol = ' '

[docker_context]
symbol = ' '

[dotnet]
symbol = ' '
format = '[$symbol($version )($tfm )]($style)'

[elixir]
symbol = ' '
format = '[$symbol($version \(OTP $otp_version\) )]($style)'

[elm]
symbol = ' '
format = '[$symbol($version )]($style)'

[erlang]
symbol = ' '
format = '[$symbol($version )]($style)'

[fennel]
symbol = ' '
format = '[$symbol($version )]($style)'

[fortran]
symbol = ' '
format = '[$symbol($version(-$name) )]($style)'

[fossil_branch]
symbol = ' '

[gcloud]
symbol = '󱇶 '

[gleam]
symbol = ' '
format = '[$symbol($version )]($style)'

[git_commit]
tag_symbol = '  '

[golang]
symbol = ' '
format = '[$symbol($version )]($style)'

[gradle]
symbol = ' '
format = '[$symbol($version )]($style)'

[guix_shell]
symbol = ' '
format = '[$symbol]($style) '

[haskell]
symbol = ' '
format = '[$symbol($version )]($style)'

[haxe]
symbol = ' '
format = '[$symbol($version )]($style)'

[helm]
symbol = ' '
format = '[$symbol($version )]($style)'

[hg_branch]
symbol = ' '

[java]
symbol = ' '
format = '[$symbol($version )]($style)'

[julia]
symbol = ' '
format = '[$symbol($version )]($style)'

[kotlin]
symbol = ' '
format = '[$symbol($version )]($style)'

[kubernetes]
symbol = '󱃾 '

[lua]
symbol = ' '
format = '[$symbol($version )]($style)'

[maven]
symbol = ' '
format = '[$symbol($version )]($style)'

[memory_usage]
symbol = '󰍛 '

[meson]
symbol = '󰔷 '
format = '[$symbol$project]($style) '

[mojo]
symbol = '󰈸 '
format = '[$symbol($version )]($style)'

[nats]
symbol = ' '

[netns]
symbol = '󰛳 '

[nim]
symbol = ' '
format = '[$symbol($version )]($style)'

[nix_shell]
symbol = ' '
format = '[$symbol$state( \($name\))]($style) '

[nodejs]
symbol = ' '
format = '[$symbol($version )]($style)'

[ocaml]
symbol = ' '
format = '[$symbol($version )(\($switch_indicator$switch_name\) )]($style)'

[odin]
symbol = '󰟢 '
format = '[$symbol($version )]($style)'

[opa]
symbol = ' '
format = '[$symbol($version )]($style)'

[openstack]
symbol = ' '

[perl]
symbol = ' '
format = '[$symbol($version )]($style)'

[php]
symbol = ' '
format = '[$symbol($version )]($style)'

[pijul_channel]
symbol = ' '

[pixi]
symbol = '󰏗 '
format = '[$symbol($version )(\($environment\) )]($style)'

[pulumi]
symbol = ' '
format = '[$symbol($username@)$stack]($style) '

[purescript]
symbol = ' '
format = '[$symbol($version )]($style)'

[python]
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[quarto]
symbol = '󰠜 '
format = '[$symbol($version )]($style)'

[raku]
symbol = '󱖊 '
format = '[$symbol($version-$vm_version )]($style)'

[red]
symbol = '󱍼 '
format = '[$symbol($version )]($style)'

[rlang]
symbol = '󰟔 '
format = '[$symbol($version )]($style)'

[ruby]
symbol = ' '
format = '[$symbol($version )]($style)'

[rust]
symbol = '󱘗 '
format = '[$symbol($version )]($style)'

[scala]
symbol = ' '
format = '[$symbol($version )]($style)'

[shlvl]
symbol = '󰹍 '

[singularity]
symbol = ' '

[solidity]
symbol = ' '
format = '[$symbol($version )]($style)'

[spack]
symbol = ' '
format = '[$symbol$environment]($style) '

[status]
symbol = ' '

[sudo]
symbol = ' '

[swift]
symbol = ' '
format = '[$symbol($version )]($style)'

[terraform]
symbol = ' '
format = '[$symbol$workspace]($style) '

[typst]
symbol = ' '
format = '[$symbol($version )]($style)'

[vagrant]
symbol = ' '
format = '[$symbol($version )]($style)'

[vlang]
symbol = ' '
format = '[$symbol($version )]($style)'

[xmake]
symbol = ' '
format = '[$symbol($version )]($style)'

[zig]
symbol = ' '
format = '[$symbol($version )]($style)'

# OS ICON
[os.symbols]
AIX = " "
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
ALTLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
Bluefin = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = " "
InstantOS = " "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = "󰺡 "
PikaOS = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Redox = "󰀘 "
RockyLinux = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Ultramarine = " "
Unknown = " "
Uos = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# mauve = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"
