add_newline = false

format = """
$os\
$directory\
$all\
$character\
"""

# right_format= """
# """

# [line_break]
# disabled = true

[os]
disabled = false
format = '[$symbol]($style)'

# [username]
# disabled = false
# show_always = true
# style_user = 'bold green'
# format = '[$user]($style)'
#
# [hostname]
# ssh_only = false
# ssh_symbol = "󰢹 "
# style = 'bold blue'
# format = '[$hostname]($style)[$ssh_symbol]($style)'

[directory]
# style = 'bold blue'
format = '[$path]($style) '
truncation_length = 3

[character]
success_symbol = '[➔](bold green)'
error_symbol = '[✘](bold red)'
vimcmd_symbol = '[V](bold green)'
# success_symbol = '[\$](bold green)'
# error_symbol = '[\$](red bold)'


# OS ICON
[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = "󰀵 "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

# Language Icon
[c]
symbol = " "
format = '[$symbol($version(-$name) )]($style)'

[cpp]
symbol = "󰙲 "
format = '[$symbol($version(-$name) )]($style)'

[lua]
symbol = " "
format = '[$symbol($version )]($style)'

[java]
symbol = " "
format = '[${symbol}(${version} )]($style)'

[cmake]
format = '[$symbol($version)]($style) '

[conda]
symbol = " "
format = '[$symbol$environment]($style) '

[docker_context]
symbol = " "
format = '[$symbol$context]($style) '

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
symbol = "󰎙 "
format = '[$symbol($version)]($style)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[hg_branch]
format = '[$symbol$branch(:$topic)]($style)'

[pijul_channel]
format = '[$symbol$channel]($style)'

[aws]
symbol = " "

[buf]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "
format = '[$symbol$version]($style) '

[perl]
symbol = " "

[php]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

# $os\
# $username[@](bold)\
# $hostname[:](bold)\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $hg_branch\
# $pijul_channel\

# palette = 'catppuccin_mocha'
# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# mauve = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"
