local M = {}

M.diagnostics = {
  Error = '󰅚',
  Warn = '󰀪',
  Info = '󰋽',
  Hint = '󰌶',
}

M.git = {
  Branch = '',
  Dirty = '*',
  Added = '',
  Removed = '',
  Changed = '',
}

M.status = {
  DefaultFile = '󰈙',
  Terminal = '',
  Modified = '[+]',
  Readonly = '',
  Lsp = '',
  Search = '',
  Macro = '',
  Mode = '',
  Spinner = '',
  Line = '',
  Column = '',
  Position = '󰍒',
}

M.dashboard = {
  FindFile = { icon = '󰈞 ', hl = 'icon' },
  NewFile = { icon = '󰈔 ', hl = 'icon' },
  FindText = { icon = '󰱼 ', hl = 'icon' },
  RecentFiles = { icon = '󰋚 ', hl = 'icon' },
  Config = { icon = '󰒓 ', hl = 'icon' },
  RestoreSession = { icon = '󰦛 ', hl = 'icon' },
  Mason = { icon = '󰏗 ', hl = 'icon' },
  Packages = { icon = '󰒲 ', hl = 'icon' },
  Quit = { icon = '󰗼 ', hl = 'icon' },
}

M.which_key = {
  buffer = { icon = ' ', color = 'blue' },
  code = { icon = ' ', color = 'azure' },
  debug = { icon = ' ', color = 'red' },
  git = { icon = ' ', color = 'orange' },
  file = { icon = '󰈞 ', color = 'blue' },
  hunk = { icon = '󰊢 ', color = 'orange' },
  lsp = { icon = ' ', color = 'green' },
  search = { icon = ' ', color = 'cyan' },
  toggle = { icon = ' ', color = 'yellow' },
  ui = { icon = '󰙵 ', color = 'cyan' },
  ['goto'] = { icon = '󰿅 ', color = 'purple' },
  fold = { icon = ' ', color = 'purple' },
}

M.which_key_items = {
  smart_files = { icon = '󰈞 ', color = 'blue' },
  buffers = { icon = ' ', color = 'blue' },
  grep = { icon = ' ', color = 'cyan' },
  command_history = { icon = ' ', color = 'yellow' },
  breakpoint = { icon = ' ', color = 'red' },
  diagnostics = { icon = ' ', color = 'yellow' },
  explorer = { icon = ' ', color = 'blue' },
  outline = { icon = '󰙅 ', color = 'green' },
  notifications = { icon = ' ', color = 'purple' },
  news = { icon = ' ', color = 'cyan' },
  scratch = { icon = ' ', color = 'green' },
  scratch_select = { icon = '󰒮 ', color = 'green' },
  zen = { icon = '󱅻 ', color = 'purple' },
  zoom = { icon = ' ', color = 'cyan' },
  buffer_delete = { icon = '󰆴 ', color = 'red' },
  format = { icon = ' ', color = 'cyan' },
  rename = { icon = '󰑕 ', color = 'orange' },
  rename_file = { icon = '󰈔 ', color = 'orange' },
  breakpoint_condition = { icon = ' ', color = 'yellow' },
  find_config = { icon = ' ', color = 'blue' },
  find_files = { icon = '󰈞 ', color = 'blue' },
  git_files = { icon = ' ', color = 'orange' },
  projects = { icon = '󰏗 ', color = 'blue' },
  recent = { icon = '󰋚 ', color = 'cyan' },
  git_branches = { icon = ' ', color = 'orange' },
  git_log = { icon = ' ', color = 'orange' },
  git_log_line = { icon = '󰜘 ', color = 'orange' },
  git_status = { icon = '󰊢 ', color = 'orange' },
  git_stash = { icon = '󰆓 ', color = 'purple' },
  git_diff = { icon = ' ', color = 'orange' },
  git_log_file = { icon = '󰈙 ', color = 'orange' },
  git_browse = { icon = '󰖟 ', color = 'blue' },
  lazygit = { icon = ' ', color = 'orange' },
  hunk_stage = { icon = ' ', color = 'green' },
  hunk_reset = { icon = ' ', color = 'red' },
  buffer_stage = { icon = '󰒋 ', color = 'green' },
  undo = { icon = ' ', color = 'yellow' },
  buffer_reset = { icon = '󰑐 ', color = 'red' },
  preview = { icon = ' ', color = 'cyan' },
  blame = { icon = '󰊢 ', color = 'orange' },
  registers = { icon = '󰅍 ', color = 'blue' },
  search_history = { icon = ' ', color = 'yellow' },
  autocmds = { icon = '󰑓 ', color = 'purple' },
  buffer_lines = { icon = ' ', color = 'blue' },
  commands = { icon = ' ', color = 'yellow' },
  help = { icon = '󰋖 ', color = 'blue' },
  highlights = { icon = '󰸱 ', color = 'yellow' },
  icons = { icon = '󰲂 ', color = 'purple' },
  jumps = { icon = '󰁔 ', color = 'purple' },
  keymaps = { icon = '󰌌 ', color = 'cyan' },
  loclist = { icon = '󰍉 ', color = 'yellow' },
  marks = { icon = '󰃀 ', color = 'purple' },
  man = { icon = '󰈙 ', color = 'blue' },
  plugin_spec = { icon = '󰒲 ', color = 'purple' },
  quickfix = { icon = ' ', color = 'yellow' },
  resume = { icon = '󰑓 ', color = 'green' },
  lsp_symbols = { icon = '󰒕 ', color = 'green' },
  lsp_workspace_symbols = { icon = '󰒕 ', color = 'cyan' },
  colorschemes = { icon = '󰏘 ', color = 'purple' },
  dismiss_notifications = { icon = '󰎟 ', color = 'red' },
  spelling = { icon = '󰓆 ', color = 'green' },
  wrap = { icon = '󰖶 ', color = 'cyan' },
  relative_number = { icon = '󰉻 ', color = 'yellow' },
  line_number = { icon = '󰉻 ', color = 'yellow' },
  conceal = { icon = '󰈉 ', color = 'purple' },
  treesitter = { icon = '󰔱 ', color = 'green' },
  background = { icon = '󰔎 ', color = 'yellow' },
  inlay_hints = { icon = '󰌶 ', color = 'green' },
  indent = { icon = '󰉶 ', color = 'cyan' },
  dim = { icon = '󰖨 ', color = 'purple' },
  git_deleted = { icon = ' ', color = 'red' },
  goto_definition = { icon = '󰿕 ', color = 'purple' },
  goto_declaration = { icon = '󰿄 ', color = 'purple' },
  goto_implementation = { icon = '󰡶 ', color = 'purple' },
  goto_type = { icon = '󰉺 ', color = 'purple' },
  references = { icon = '󰌹 ', color = 'purple' },
  code_action = { icon = '󰌵 ', color = 'yellow' },
  next_reference = { icon = '󰮻 ', color = 'green' },
  prev_reference = { icon = '󰮻 ', color = 'green' },
  next_hunk = { icon = '󰊢 ', color = 'orange' },
  prev_hunk = { icon = '󰊢 ', color = 'orange' },
  flash = { icon = '󰈈 ', color = 'cyan' },
  flash_treesitter = { icon = '󰈈 ', color = 'cyan' },
  terminal = { icon = '󰆍 ', color = 'green' },
  buffer_prev = { icon = '󰮛 ', color = 'blue' },
  buffer_next = { icon = '󰮜 ', color = 'blue' },
}

M.dap = {
  ui = {
    expanded = '',
    collapsed = '',
    current_frame = '',
  },
  controls = {
    pause = '',
    play = '',
    step_into = '',
    step_over = '',
    step_out = '',
    step_back = '',
    run_last = '',
    terminate = '',
    disconnect = '',
  },
  breakpoints = {
    Breakpoint = '',
    BreakpointCondition = '',
    BreakpointRejected = '',
    LogPoint = '',
    Stopped = '',
  },
}

return M
