local icons = require 'config.icons'

require('which-key').setup {
  preset = 'helix',
  delay = 0,
  icons = {
    -- set icon mappings to true if you have a Nerd Font
    -- breadcrumb = '»', -- symbol used in the command line area that shows your active key combo
    -- separator = '➜', -- symbol used between a key and it's label
    -- group = '+', -- symbol prepended to a group
    -- ellipsis = '…',

    keys = {
      Up = '<Up>',
      Down = '<Down>',
      Left = '<Left>',
      Right = '<Right>',
      C = '<C-…>',
      M = '<M-…>',
      D = '<D-…>',
      S = '<S-…>',
      CR = '<CR>',
      Esc = '<Esc>',
      ScrollWheelDown = '󱕐',
      ScrollWheelUp = '󱕑',
      NL = '<NL>',
      BS = '<BS>',
      Space = '󱁐',
      Tab = '<Tab>',
      F1 = '<F1>',
      F2 = '<F2>',
      F3 = '<F3>',
      F4 = '<F4>',
      F5 = '<F5>',
      F6 = '<F6>',
      F7 = '<F7>',
      F8 = '<F8>',
      F9 = '<F9>',
      F10 = '<F10>',
      F11 = '<F11>',
      F12 = '<F12>',
    },
  },

  -- Document existing key chains
  spec = {
    { '<leader><space>', icon = icons.which_key_items.smart_files },
    { '<leader>,', icon = icons.which_key_items.buffers },
    { '<leader>/', icon = icons.which_key_items.grep },
    { '<leader>:', icon = icons.which_key_items.command_history },
    { '<leader>e', icon = icons.which_key_items.explorer },
    { '<leader>n', icon = icons.which_key_items.notifications },
    { '<leader>N', icon = icons.which_key_items.news },
    { '<leader>q', icon = icons.which_key_items.diagnostics },
    { '<leader>.', icon = icons.which_key_items.scratch },
    { '<leader>S', icon = icons.which_key_items.scratch_select },
    { '<leader>z', icon = icons.which_key_items.zen },
    { '<leader>Z', icon = icons.which_key_items.zoom },
    { '<leader>b', group = 'Buffer', icon = icons.which_key.buffer },
    { '<leader>c', group = 'Code', icon = icons.which_key.code },
    { '<leader>d', group = 'Debug', icon = icons.which_key.debug },
    { '<leader>g', group = 'Git', icon = icons.which_key.git },
    { '<leader>f', group = 'File/Find', icon = icons.which_key.file },
    { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' }, icon = icons.which_key.hunk },
    { '<leader>l', group = 'Lsp', mode = 'n', icon = icons.which_key.lsp },
    { '<leader>s', group = 'Search', icon = icons.which_key.search },
    { '<leader>t', group = 'Toggle', icon = icons.which_key.toggle },
    { '<leader>o', icon = icons.which_key_items.outline },
    { '<leader>u', group = 'UI', icon = icons.which_key.ui },
    { '<leader>bd', icon = icons.which_key_items.buffer_delete },
    { '<leader>cf', icon = icons.which_key_items.format },
    { '<leader>cr', icon = icons.which_key_items.rename },
    { '<leader>cR', icon = icons.which_key_items.rename_file },
    { '<leader>db', icon = icons.which_key_items.breakpoint },
    { '<leader>dB', icon = icons.which_key_items.breakpoint_condition },
    { '<leader>fb', icon = icons.which_key_items.buffers },
    { '<leader>fc', icon = icons.which_key_items.find_config },
    { '<leader>ff', icon = icons.which_key_items.find_files },
    { '<leader>fg', icon = icons.which_key_items.git_files },
    { '<leader>fp', icon = icons.which_key_items.projects },
    { '<leader>fr', icon = icons.which_key_items.recent },
    { '<leader>gb', icon = icons.which_key_items.git_branches },
    { '<leader>gl', icon = icons.which_key_items.git_log },
    { '<leader>gL', icon = icons.which_key_items.git_log_line },
    { '<leader>gs', icon = icons.which_key_items.git_status },
    { '<leader>gS', icon = icons.which_key_items.git_stash },
    { '<leader>gd', icon = icons.which_key_items.git_diff },
    { '<leader>gf', icon = icons.which_key_items.git_log_file },
    { '<leader>gB', mode = { 'n', 'v' }, icon = icons.which_key_items.git_browse },
    { '<leader>gg', icon = icons.which_key_items.lazygit },
    { '<leader>hs', mode = { 'n', 'v' }, icon = icons.which_key_items.hunk_stage },
    { '<leader>hr', mode = { 'n', 'v' }, icon = icons.which_key_items.hunk_reset },
    { '<leader>hS', icon = icons.which_key_items.buffer_stage },
    { '<leader>hu', icon = icons.which_key_items.undo },
    { '<leader>hR', icon = icons.which_key_items.buffer_reset },
    { '<leader>hp', icon = icons.which_key_items.preview },
    { '<leader>hb', icon = icons.which_key_items.blame },
    { '<leader>hd', icon = icons.which_key_items.git_diff },
    { '<leader>hD', icon = icons.which_key_items.git_diff },
    { '<leader>sB', icon = icons.which_key_items.buffer_lines },
    { '<leader>sg', icon = icons.which_key_items.grep },
    { '<leader>sw', mode = { 'n', 'x' }, icon = icons.which_key_items.grep },
    { '<leader>s"', icon = icons.which_key_items.registers },
    { '<leader>s/', icon = icons.which_key_items.search_history },
    { '<leader>sa', icon = icons.which_key_items.autocmds },
    { '<leader>sb', icon = icons.which_key_items.buffer_lines },
    { '<leader>sc', icon = icons.which_key_items.command_history },
    { '<leader>sC', icon = icons.which_key_items.commands },
    { '<leader>sd', icon = icons.which_key_items.diagnostics },
    { '<leader>sD', icon = icons.which_key_items.diagnostics },
    { '<leader>sh', icon = icons.which_key_items.help },
    { '<leader>sH', icon = icons.which_key_items.highlights },
    { '<leader>si', icon = icons.which_key_items.icons },
    { '<leader>sj', icon = icons.which_key_items.jumps },
    { '<leader>sk', icon = icons.which_key_items.keymaps },
    { '<leader>sl', icon = icons.which_key_items.loclist },
    { '<leader>sm', icon = icons.which_key_items.marks },
    { '<leader>sM', icon = icons.which_key_items.man },
    { '<leader>sp', icon = icons.which_key_items.plugin_spec },
    { '<leader>sq', icon = icons.which_key_items.quickfix },
    { '<leader>sR', icon = icons.which_key_items.resume },
    { '<leader>ss', icon = icons.which_key_items.lsp_symbols },
    { '<leader>sS', icon = icons.which_key_items.lsp_workspace_symbols },
    { '<leader>su', icon = icons.which_key_items.undo },
    { '<leader>tb', icon = icons.which_key_items.blame },
    { '<leader>tD', icon = icons.which_key_items.git_deleted },
    { '<leader>uC', icon = icons.which_key_items.colorschemes },
    { '<leader>un', icon = icons.which_key_items.dismiss_notifications },
    { '<leader>us', icon = icons.which_key_items.spelling },
    { '<leader>uw', icon = icons.which_key_items.wrap },
    { '<leader>uL', icon = icons.which_key_items.relative_number },
    { '<leader>ud', icon = icons.which_key_items.diagnostics },
    { '<leader>ul', icon = icons.which_key_items.line_number },
    { '<leader>uc', icon = icons.which_key_items.conceal },
    { '<leader>uT', icon = icons.which_key_items.treesitter },
    { '<leader>ub', icon = icons.which_key_items.background },
    { '<leader>uh', icon = icons.which_key_items.inlay_hints },
    { '<leader>ug', icon = icons.which_key_items.indent },
    { '<leader>uD', icon = icons.which_key_items.dim },
    { 'g', group = 'Go to', icon = icons.which_key['goto'] },
    { 'gd', icon = icons.which_key_items.goto_definition },
    { 'gD', icon = icons.which_key_items.goto_declaration },
    { 'gr', icon = icons.which_key_items.references },
    { 'gI', icon = icons.which_key_items.goto_implementation },
    { 'gy', icon = icons.which_key_items.goto_type },
    { 'ga', icon = icons.which_key_items.code_action },
    { 'grn', icon = icons.which_key_items.rename },
    { 'gra', icon = icons.which_key_items.code_action },
    { 'grr', icon = icons.which_key_items.references },
    { 'gri', icon = icons.which_key_items.goto_implementation },
    { 'grt', icon = icons.which_key_items.goto_type },
    { ']]', icon = icons.which_key_items.next_reference },
    { '[[', icon = icons.which_key_items.prev_reference },
    { ']c', icon = icons.which_key_items.next_hunk },
    { '[c', icon = icons.which_key_items.prev_hunk },
    { 'ss', icon = icons.which_key_items.flash },
    { 'SS', icon = icons.which_key_items.flash_treesitter },
    { '<c-/>', icon = icons.which_key_items.terminal },
    { '<S-h>', icon = icons.which_key_items.buffer_prev },
    { '<S-l>', icon = icons.which_key_items.buffer_next },
    { 'z', group = 'Fold', icon = icons.which_key.fold },
  },
}
